[package]
name = "metadata"
version = "0.1.0"
edition = "2024"

[dependencies]
lofty = "0.22.4"
log = "0.4.27"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"

[dev-dependencies]
test-log = "0.2.18"
