[package]
name = "music-manager"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
axum = "0.7.9"
color-eyre = "0.6.3"
diesel = { version = "2.2.6", features = ["serde_json", "sqlite", "time", "uuid"] }
id3 = { version = "1.16.0", features = ["tokio"] }
image = { version = "0.25.5", features = ["serde"] }
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
metaflac = "0.2.7"
mime_guess = "2.0.5"
reqwest = "0.12.9"
rust-embed = "8.5.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
tokio = { version = "1.42.0", features = ["full"] }
